apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuance-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issuance
  template:
    metadata:
      labels:
        app: issuance
    spec:
      containers:
        - name: issuance
          image: zupple-issuance-service:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: issuance-service
spec:
  selector:
    app: issuance
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
